apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: java
spec:
  type: LoadBalancer
  selector:
    app: vproapp         # Points to the Tomcat application pods
  ports:
  - port: 80             # External port for users
    targetPort: 8080     # Tomcat's application port
    protocol: TCP
